// The ONLY way the UI calls the backend: the generated Wails bindings. These
// thin wrappers re-type the results to our component-facing interfaces (types.ts)
// and centralize the call surface so views never import bindings directly.
import {
  GetState,
  GetRoutes,
  GetInterfaces,
  Explain,
  GetProfiles,
  GetAudit,
  GetSnapshots,
  GetDoctor,
  GetLeaks,
  SetKillSwitch,
  PlanPreview,
  Apply,
  Confirm,
  Rollback,
  PanicFlush,
  SetProfileEnabled,
  Reachable,
  Version,
  GetDaemonInfo,
  InstallDaemon,
  StartDaemon,
  StopDaemon,
  RestartDaemon,
  UninstallDaemon,
} from '../../wailsjs/go/main/App'
import type {
  State,
  Route,
  Iface,
  RouteExplain,
  Profile,
  Plan,
  ApplyResult,
  AuditEvent,
  Snapshot,
  DoctorReport,
  Leak,
  DaemonInfo,
} from '../types'

export const api = {
  state: () => GetState() as unknown as Promise<State>,
  routes: (family = '', owner = '') => GetRoutes(family, owner) as unknown as Promise<Route[]>,
  interfaces: () => GetInterfaces() as unknown as Promise<Iface[]>,
  explain: (target: string) => Explain(target) as unknown as Promise<RouteExplain>,
  profiles: () => GetProfiles() as unknown as Promise<Profile[]>,
  audit: () => GetAudit() as unknown as Promise<AuditEvent[]>,
  snapshots: () => GetSnapshots() as unknown as Promise<Snapshot[]>,
  doctor: () => GetDoctor() as unknown as Promise<DoctorReport>,
  leaks: () => GetLeaks() as unknown as Promise<Leak[]>,
  setKillSwitch: (enabled: boolean) => SetKillSwitch(enabled) as Promise<boolean>,
  plan: () => PlanPreview() as unknown as Promise<Plan>,
  apply: (yes: boolean, confirmTimeoutSec: number) => Apply(yes, confirmTimeoutSec) as unknown as Promise<ApplyResult>,
  confirm: (txID: string) => Confirm(txID) as unknown as Promise<string>,
  rollback: (txID: string) => Rollback(txID) as unknown as Promise<string>,
  panic: () => PanicFlush() as Promise<void>,
  setProfileEnabled: (name: string, enable: boolean) =>
    SetProfileEnabled(name, enable) as unknown as Promise<ApplyResult>,
  reachable: () => Reachable() as Promise<boolean>,
  version: () => Version() as Promise<string>,
  // Daemon lifecycle (privileged ops prompt for admin via the OS).
  daemonInfo: () => GetDaemonInfo() as unknown as Promise<DaemonInfo>,
  installDaemon: () => InstallDaemon() as Promise<void>,
  startDaemon: () => StartDaemon() as Promise<void>,
  stopDaemon: () => StopDaemon() as Promise<void>,
  restartDaemon: () => RestartDaemon() as Promise<void>,
  uninstallDaemon: () => UninstallDaemon() as Promise<void>,
}
