// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {safety} from '../models';
import {domain} from '../models';

export function Apply(arg1:boolean,arg2:number):Promise<safety.Result>;

export function Confirm(arg1:string):Promise<domain.TxResult>;

export function Explain(arg1:string):Promise<domain.RouteExplain>;

export function GetAudit():Promise<Array<domain.AuditEvent>>;

export function GetInterfaces():Promise<Array<domain.Iface>>;

export function GetProfiles():Promise<Array<domain.Profile>>;

export function GetRoutes(arg1:string,arg2:string):Promise<Array<domain.Route>>;

export function GetSnapshots():Promise<Array<domain.Snapshot>>;

export function GetState():Promise<domain.State>;

export function PanicFlush():Promise<void>;

export function PlanPreview():Promise<domain.Plan>;

export function Reachable():Promise<boolean>;

export function Rollback(arg1:string):Promise<domain.TxResult>;

export function SetProfileEnabled(arg1:string,arg2:boolean):Promise<safety.Result>;

export function Version():Promise<string>;
