// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {safety} from '../models';
import {apiclient} from '../models';
import {update} from '../models';
import {domain} from '../models';
import {main} from '../models';
import {sysinfo} from '../models';

export function Apply(arg1:boolean,arg2:number):Promise<safety.Result>;

export function ApplyConfigContent(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<apiclient.ConfigResult>;

export function CheckUpdate():Promise<update.Result>;

export function Confirm(arg1:string):Promise<domain.TxResult>;

export function DeleteList(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<apiclient.ConfigResult>;

export function Explain(arg1:string):Promise<domain.RouteExplain>;

export function ExportConfigDialog():Promise<string>;

export function GetAudit():Promise<Array<domain.AuditEvent>>;

export function GetDaemonInfo():Promise<main.DaemonInfo>;

export function GetDoctor():Promise<domain.DoctorReport>;

export function GetFlows():Promise<Array<domain.Flow>>;

export function GetInterfaces():Promise<Array<domain.Iface>>;

export function GetLeaks():Promise<Array<domain.Leak>>;

export function GetLists():Promise<Array<domain.List>>;

export function GetProfiles():Promise<Array<domain.Profile>>;

export function GetRoutes(arg1:string,arg2:string):Promise<Array<domain.Route>>;

export function GetRules():Promise<Array<domain.PolicyRule>>;

export function GetSnapshots():Promise<Array<domain.Snapshot>>;

export function GetSplitDNS():Promise<Array<domain.SplitDNSRoute>>;

export function GetState():Promise<domain.State>;

export function GetSystemApps():Promise<Array<sysinfo.App>>;

export function GetSystemUsers():Promise<Array<sysinfo.User>>;

export function InstallDaemon():Promise<void>;

export function OpenConfigDialog():Promise<main.ConfigFile>;

export function PanicFlush():Promise<void>;

export function PlanPreview():Promise<domain.Plan>;

export function Reachable():Promise<boolean>;

export function RefreshList(arg1:string):Promise<domain.List>;

export function RestartDaemon():Promise<void>;

export function RestoreSnapshot(arg1:string):Promise<apiclient.ConfigResult>;

export function Rollback(arg1:string):Promise<domain.TxResult>;

export function RouteOp(arg1:string,arg2:domain.Route,arg3:domain.Route):Promise<apiclient.ConfigResult>;

export function SaveList(arg1:domain.List):Promise<domain.List>;

export function SaveProfile(arg1:domain.Profile,arg2:boolean):Promise<apiclient.ConfigResult>;

export function SetAutoApply(arg1:boolean):Promise<boolean>;

export function SetKillSwitch(arg1:boolean):Promise<boolean>;

export function SetProfileEnabled(arg1:string,arg2:boolean):Promise<safety.Result>;

export function SetSplitDNS(arg1:Array<domain.SplitDNSRoute>):Promise<Array<domain.SplitDNSRoute>>;

export function StartDaemon():Promise<void>;

export function StopDaemon():Promise<void>;

export function UninstallDaemon():Promise<void>;

export function Version():Promise<string>;
