// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Apply(arg1, arg2) {
  return window['go']['main']['App']['Apply'](arg1, arg2);
}

export function Confirm(arg1) {
  return window['go']['main']['App']['Confirm'](arg1);
}

export function Explain(arg1) {
  return window['go']['main']['App']['Explain'](arg1);
}

export function GetAudit() {
  return window['go']['main']['App']['GetAudit']();
}

export function GetDoctor() {
  return window['go']['main']['App']['GetDoctor']();
}

export function GetInterfaces() {
  return window['go']['main']['App']['GetInterfaces']();
}

export function GetLeaks() {
  return window['go']['main']['App']['GetLeaks']();
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function GetRoutes(arg1, arg2) {
  return window['go']['main']['App']['GetRoutes'](arg1, arg2);
}

export function GetSnapshots() {
  return window['go']['main']['App']['GetSnapshots']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function PanicFlush() {
  return window['go']['main']['App']['PanicFlush']();
}

export function PlanPreview() {
  return window['go']['main']['App']['PlanPreview']();
}

export function Reachable() {
  return window['go']['main']['App']['Reachable']();
}

export function Rollback(arg1) {
  return window['go']['main']['App']['Rollback'](arg1);
}

export function SetKillSwitch(arg1) {
  return window['go']['main']['App']['SetKillSwitch'](arg1);
}

export function SetProfileEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetProfileEnabled'](arg1, arg2);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
