// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Explain(arg1) {
  return window['go']['main']['App']['Explain'](arg1);
}

export function GetAudit() {
  return window['go']['main']['App']['GetAudit']();
}

export function GetInterfaces() {
  return window['go']['main']['App']['GetInterfaces']();
}

export function GetProfiles() {
  return window['go']['main']['App']['GetProfiles']();
}

export function GetRoutes(arg1, arg2) {
  return window['go']['main']['App']['GetRoutes'](arg1, arg2);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function Reachable() {
  return window['go']['main']['App']['Reachable']();
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
